language: python
python:
  - "3.4"
  - "3.5"

sudo: false

addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

install:
  - cd ..
  - mkdir cortoproject
  - mv python-binding cortoproject/python-binding
  - cd cortoproject
  - git clone https://github.com/cortoproject/corto.git
  - git clone https://github.com/cortoproject/c-binding.git
  - git clone https://github.com/cortoproject/xml.git
  - git clone https://github.com/cortoproject/corto-language.git
  - git clone https://github.com/cortoproject/io.git
  - git clone https://github.com/cortoproject/cortodoc.git
  - git clone https://github.com/cortoproject/test.git
  - |+
    echo 'COMPONENTS = %w(corto c-binding xml corto-language io cortodoc test)
    require "#{ENV["CORTO_BUILD"]}/forward"' > rakefile
  - source corto/configure
  - rake
  - cd python-binding
  - pip install -r requirements-dev.txt
  - export LD_LIBRARY_PATH="$HOME/.corto/lib/corto/0.2/packages/corto"

script:
  - rake
